#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC12B8E73B30F2FC8 (infra-root@openstack.org)
#
Name     : oslo.db
Version  : 8.2.1
Release  : 70
URL      : https://tarballs.openstack.org/oslo.db/oslo.db-8.2.1.tar.gz
Source0  : https://tarballs.openstack.org/oslo.db/oslo.db-8.2.1.tar.gz
Source1  : https://tarballs.openstack.org/oslo.db/oslo.db-8.2.1.tar.gz.asc
Summary  : Oslo Database library
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.db-license = %{version}-%{release}
Requires: oslo.db-python = %{version}-%{release}
Requires: oslo.db-python3 = %{version}-%{release}
Requires: PyMySQL
Requires: SQLAlchemy
Requires: alembic
Requires: debtcollector
Requires: oslo.config
Requires: oslo.i18n
Requires: oslo.utils
Requires: pbr
Requires: psycopg2
Requires: sqlalchemy-migrate
Requires: stevedore
Requires: testresources
Requires: testscenarios
BuildRequires : PyMySQL
BuildRequires : SQLAlchemy
BuildRequires : alembic
BuildRequires : buildreq-distutils3
BuildRequires : debtcollector
BuildRequires : oslo.config
BuildRequires : oslo.i18n
BuildRequires : oslo.utils
BuildRequires : pbr
BuildRequires : psycopg2
BuildRequires : sqlalchemy-migrate
BuildRequires : stevedore
BuildRequires : testresources
BuildRequires : testscenarios

%description
Team and repository tags
        ========================

%package license
Summary: license components for the oslo.db package.
Group: Default

%description license
license components for the oslo.db package.


%package python
Summary: python components for the oslo.db package.
Group: Default
Requires: oslo.db-python3 = %{version}-%{release}

%description python
python components for the oslo.db package.


%package python3
Summary: python3 components for the oslo.db package.
Group: Default
Requires: python3-core
Provides: pypi(oslo.db)
Requires: pypi(alembic)
Requires: pypi(debtcollector)
Requires: pypi(oslo.config)
Requires: pypi(oslo.i18n)
Requires: pypi(oslo.utils)
Requires: pypi(pbr)
Requires: pypi(sqlalchemy)
Requires: pypi(sqlalchemy_migrate)
Requires: pypi(stevedore)
Requires: pypi(testresources)
Requires: pypi(testscenarios)

%description python3
python3 components for the oslo.db package.


%prep
%setup -q -n oslo.db-8.2.1
cd %{_builddir}/oslo.db-8.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1594662912
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/oslo.db
cp %{_builddir}/oslo.db-8.2.1/LICENSE %{buildroot}/usr/share/package-licenses/oslo.db/57aed0b0f74e63f6b85cce11bce29ba1710b422b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/oslo.db/57aed0b0f74e63f6b85cce11bce29ba1710b422b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
